

[general]
import = ["colors.toml",]

[window]
padding.x = 10
padding.y = 10
opacity = 0.7
blur = true


[font]
normal.family = "Terminess Nerd Font Propo"
normal.style = "Regular"

bold.family = "Terminess Nerd Font"
bold.style = "Bold"

italic.family = "Terminess Nerd Font"
italic.style = "Italic"

bold_italic.family = "Terminess Nerd Font"
bold_italic.style = "Bold Italic"

size = 11


[cursor]
style.shape = "Underline"
style.blinking = "Always"

blink_interval = 500
